export const postgresTables=[
  `CREATE TABLE IF NOT EXISTS user_admins (
    user_id VARCHAR(36) PRIMARY KEY
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(36) NOT NULL, started_at BIGINT NOT NULL, completed_at BIGINT NOT NULL,
    actor_type VARCHAR(16) NOT NULL, actor_id VARCHAR(36),
    ip VARCHAR(64) NOT NULL, peer_ip VARCHAR(64) NOT NULL, user_agent VARCHAR(512) NOT NULL,
    method VARCHAR(8) NOT NULL, action VARCHAR(64) NOT NULL, target_id VARCHAR(36),
    status INTEGER NOT NULL, changes JSONB NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS ix_audit_target ON audit_logs(target_id,id)`,
  `CREATE INDEX IF NOT EXISTS ix_audit_time ON audit_logs(completed_at)`,
  `CREATE TABLE IF NOT EXISTS user_info (
    id VARCHAR(36) PRIMARY KEY, email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(256) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON user_info(LOWER(email))`,
  `CREATE TABLE IF NOT EXISTS tg_info (
    account_id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL,
    api_id BIGINT NOT NULL, api_hash TEXT NOT NULL, phone TEXT NOT NULL, phone_key VARCHAR(64),
    session TEXT NOT NULL, status VARCHAR(32) NOT NULL, expires_at BIGINT,
    phone_code_hash TEXT, pending_bot TEXT, pending_channel TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS ix_tg_user ON tg_info(user_id)`,
  `CREATE TABLE IF NOT EXISTS bot_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL, account_id VARCHAR(36) NOT NULL,
    telegram_bot_id BIGINT NOT NULL UNIQUE, username VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL, token TEXT NOT NULL, customer_id VARCHAR(64),
    landing_url TEXT, card_text TEXT, card_image TEXT, button_text VARCHAR(64),
    webhook_secret TEXT, webhook_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS uq_bot_username ON bot_info(LOWER(username))`,
  `CREATE INDEX IF NOT EXISTS ix_bot_user ON bot_info(user_id)`,
  `CREATE INDEX IF NOT EXISTS ix_bot_account ON bot_info(account_id)`,
  `CREATE INDEX IF NOT EXISTS ix_bot_customer ON bot_info(customer_id)`,
  `CREATE TABLE IF NOT EXISTS channel_info (
    account_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
    request_key VARCHAR(64) COLLATE "C" NOT NULL, customer_id VARCHAR(64) NOT NULL,
    bot_username VARCHAR(32) NOT NULL, title VARCHAR(128) NOT NULL, about TEXT NOT NULL,
    channel_id VARCHAR(32), access_hash VARCHAR(32), invite_url TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'creating', posts JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_id,request_key)
  )`,
  `CREATE INDEX IF NOT EXISTS ix_channel_user ON channel_info(user_id)`,
  `CREATE TABLE IF NOT EXISTS user_security (
    user_id VARCHAR(36) PRIMARY KEY, disabled BOOLEAN NOT NULL DEFAULT FALSE,
    auth_version BIGINT NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS channel_posts (
    account_id VARCHAR(36) NOT NULL, channel_key VARCHAR(64) COLLATE "C" NOT NULL,
    request_key VARCHAR(64) COLLATE "C" NOT NULL, data JSONB NOT NULL,
    PRIMARY KEY(account_id,channel_key,request_key)
  )`,
  `CREATE TABLE IF NOT EXISTS api_jobs (
    id VARCHAR(64) PRIMARY KEY, account_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
    project_id VARCHAR(36), workflow_id VARCHAR(36),
    phone_key VARCHAR(64) NOT NULL, auth_version BIGINT NOT NULL, path VARCHAR(512) NOT NULL,
    body TEXT NOT NULL, fingerprint VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL,
    effect VARCHAR(32), result TEXT, error JSONB, lease VARCHAR(36),
    lease_until BIGINT NOT NULL DEFAULT 0, next_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS ix_jobs_pending ON api_jobs(status,next_at)`,
  `CREATE INDEX IF NOT EXISTS ix_jobs_phone ON api_jobs(phone_key,status)`,
  `CREATE TABLE IF NOT EXISTS webhook_deliveries (
    bot_id VARCHAR(32) NOT NULL, update_id VARCHAR(32) NOT NULL, payload TEXT NOT NULL,
    status VARCHAR(16) NOT NULL, attempts INTEGER NOT NULL DEFAULT 0,
    remote_message_id VARCHAR(32),
    lease VARCHAR(36), lease_until BIGINT NOT NULL DEFAULT 0, next_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY(bot_id,update_id)
  )`,
  `CREATE INDEX IF NOT EXISTS ix_deliveries_pending ON webhook_deliveries(status,next_at)`,
];
