export const tables = [
  `CREATE TABLE IF NOT EXISTS user_info (
    id CHAR(36) NOT NULL PRIMARY KEY,
    email VARCHAR(254) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    password_hash VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_user_email (email)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS tg_info (
    account_id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    api_id BIGINT UNSIGNED NOT NULL,
    api_hash CHAR(32) NOT NULL,
    phone VARCHAR(32) NOT NULL,
    session MEDIUMTEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    expires_at BIGINT NULL,
    phone_code_hash VARCHAR(256) NULL,
    pending_bot JSON NULL,
    pending_channel JSON NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY ix_tg_user (user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS bot_info (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    account_id CHAR(36) NOT NULL,
    telegram_bot_id BIGINT UNSIGNED NOT NULL,
    username VARCHAR(32) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
    name VARCHAR(64) NOT NULL,
    token VARCHAR(256) NOT NULL,
    customer_id VARCHAR(64) NULL,
    landing_url TEXT NULL,
    card_text TEXT NULL,
    card_image TEXT NULL,
    button_text VARCHAR(64) NULL,
    webhook_secret VARCHAR(64) NULL,
    webhook_url TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_bot_username (username),
    UNIQUE KEY uq_bot_telegram_id (telegram_bot_id),
    KEY ix_bot_user (user_id),
    KEY ix_bot_account (account_id),
    KEY ix_bot_customer (customer_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE IF NOT EXISTS channel_info (
    account_id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    request_key VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    customer_id VARCHAR(64) NOT NULL,
    bot_username VARCHAR(32) NOT NULL,
    title VARCHAR(128) NOT NULL,
    about TEXT NOT NULL,
    channel_id VARCHAR(32) NULL,
    access_hash VARCHAR(32) NULL,
    invite_url TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'creating',
    posts JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (account_id, request_key),
    KEY ix_channel_user (user_id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
];
