-- Administrator roles and persistent operation audit.
CREATE TABLE IF NOT EXISTS user_admins (
    user_id VARCHAR(36) PRIMARY KEY
  );

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(36) NOT NULL, started_at BIGINT NOT NULL, completed_at BIGINT NOT NULL,
    actor_type VARCHAR(16) NOT NULL, actor_id VARCHAR(36),
    ip VARCHAR(64) NOT NULL, peer_ip VARCHAR(64) NOT NULL, user_agent VARCHAR(512) NOT NULL,
    method VARCHAR(8) NOT NULL, action VARCHAR(64) NOT NULL, target_id VARCHAR(36),
    status INTEGER NOT NULL, changes JSONB NOT NULL
  );

CREATE INDEX IF NOT EXISTS ix_audit_target ON audit_logs(target_id,id);

CREATE INDEX IF NOT EXISTS ix_audit_time ON audit_logs(completed_at);

-- PostgreSQL 16+. Connect to the DB_DATABASE target before running.
-- Database creation is managed by the service or administrator, outside a transaction.

CREATE TABLE IF NOT EXISTS user_info (
    id VARCHAR(36) PRIMARY KEY, email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(256) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON user_info(LOWER(email));

CREATE TABLE IF NOT EXISTS tg_info (
    account_id VARCHAR(36) PRIMARY KEY, user_id VARCHAR(36) NOT NULL,
    api_id BIGINT NOT NULL, api_hash TEXT NOT NULL, phone TEXT NOT NULL,
    session TEXT NOT NULL, status VARCHAR(32) NOT NULL, expires_at BIGINT,
    phone_code_hash TEXT, pending_bot TEXT, pending_channel TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE INDEX IF NOT EXISTS ix_tg_user ON tg_info(user_id);

CREATE TABLE IF NOT EXISTS bot_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(36) NOT NULL, account_id VARCHAR(36) NOT NULL,
    telegram_bot_id BIGINT NOT NULL UNIQUE, username VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL, token TEXT NOT NULL, customer_id VARCHAR(64),
    landing_url TEXT, card_text TEXT, card_image TEXT, button_text VARCHAR(64),
    webhook_secret TEXT, webhook_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  );

CREATE UNIQUE INDEX IF NOT EXISTS uq_bot_username ON bot_info(LOWER(username));

CREATE INDEX IF NOT EXISTS ix_bot_user ON bot_info(user_id);

CREATE INDEX IF NOT EXISTS ix_bot_account ON bot_info(account_id);

CREATE INDEX IF NOT EXISTS ix_bot_customer ON bot_info(customer_id);

CREATE TABLE IF NOT EXISTS channel_info (
    account_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
    request_key VARCHAR(64) COLLATE "C" NOT NULL, customer_id VARCHAR(64) NOT NULL,
    bot_username VARCHAR(32) NOT NULL, title VARCHAR(128) NOT NULL, about TEXT NOT NULL,
    channel_id VARCHAR(32), access_hash VARCHAR(32), invite_url TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'creating', posts JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(account_id,request_key)
  );

CREATE INDEX IF NOT EXISTS ix_channel_user ON channel_info(user_id);

CREATE TABLE IF NOT EXISTS user_security (
    user_id VARCHAR(36) PRIMARY KEY, disabled BOOLEAN NOT NULL DEFAULT FALSE,
    auth_version BIGINT NOT NULL DEFAULT 0
  );

CREATE TABLE IF NOT EXISTS channel_posts (
    account_id VARCHAR(36) NOT NULL, channel_key VARCHAR(64) COLLATE "C" NOT NULL,
    request_key VARCHAR(64) COLLATE "C" NOT NULL, data JSONB NOT NULL,
    PRIMARY KEY(account_id,channel_key,request_key)
  );

CREATE TABLE IF NOT EXISTS api_jobs (
    id VARCHAR(64) PRIMARY KEY, account_id VARCHAR(36) NOT NULL, user_id VARCHAR(36) NOT NULL,
    phone_key VARCHAR(64) NOT NULL, auth_version BIGINT NOT NULL, path VARCHAR(512) NOT NULL,
    body TEXT NOT NULL, fingerprint VARCHAR(64) NOT NULL, status VARCHAR(16) NOT NULL,
    effect VARCHAR(32), result TEXT, error JSONB, lease VARCHAR(36),
    lease_until BIGINT NOT NULL DEFAULT 0, next_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL
  );

CREATE INDEX IF NOT EXISTS ix_jobs_pending ON api_jobs(status,next_at);

CREATE INDEX IF NOT EXISTS ix_jobs_phone ON api_jobs(phone_key,status);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
    bot_id VARCHAR(32) NOT NULL, update_id VARCHAR(32) NOT NULL, payload TEXT NOT NULL,
    status VARCHAR(16) NOT NULL, attempts INTEGER NOT NULL DEFAULT 0,
    lease VARCHAR(36), lease_until BIGINT NOT NULL DEFAULT 0, next_at BIGINT NOT NULL,
    created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, PRIMARY KEY(bot_id,update_id)
  );

CREATE INDEX IF NOT EXISTS ix_deliveries_pending ON webhook_deliveries(status,next_at);

-- Product schema additions
CREATE TABLE IF NOT EXISTS telegram_apps (id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,name VARCHAR(64) NOT NULL,api_id BIGINT NOT NULL,api_hash TEXT NOT NULL,version INT NOT NULL,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS telegram_identities (telegram_user_id VARCHAR(32) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,account_id VARCHAR(36) NOT NULL UNIQUE,profile TEXT NOT NULL,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS telegram_phone_claims (phone_key VARCHAR(64) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,account_id VARCHAR(36) NOT NULL UNIQUE,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS account_profiles (account_id VARCHAR(36) PRIMARY KEY,app_config_id VARCHAR(36),app_version INT,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS user_business (user_id VARCHAR(36) PRIMARY KEY,epoch BIGINT NOT NULL DEFAULT 0,reason VARCHAR(256),updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS user_limits (user_id VARCHAR(36) PRIMARY KEY,config TEXT NOT NULL,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS project_info (id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,account_id VARCHAR(36) NOT NULL,name VARCHAR(128) NOT NULL,customer_id VARCHAR(64) NOT NULL,status VARCHAR(16) NOT NULL,epoch BIGINT NOT NULL DEFAULT 0,draft_version INT NOT NULL,tested_version INT,published_version INT,active_workflow VARCHAR(36),created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS project_versions (project_id VARCHAR(36) NOT NULL,version INT NOT NULL,config TEXT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY(project_id,version));

CREATE TABLE IF NOT EXISTS project_resources (project_id VARCHAR(36) NOT NULL,environment VARCHAR(16) NOT NULL,kind VARCHAR(16) NOT NULL,version INT NOT NULL,bot_id VARCHAR(32) UNIQUE,username VARCHAR(32),channel_key VARCHAR(64),PRIMARY KEY(project_id,environment,kind));

CREATE TABLE IF NOT EXISTS workflow_runs (id VARCHAR(36) PRIMARY KEY,project_id VARCHAR(36) NOT NULL,user_id VARCHAR(36) NOT NULL,environment VARCHAR(16) NOT NULL,version INT NOT NULL,status VARCHAR(32) NOT NULL,business_epoch BIGINT NOT NULL,project_epoch BIGINT NOT NULL,lease VARCHAR(36),lease_until BIGINT NOT NULL DEFAULT 0,next_at BIGINT NOT NULL,created_at BIGINT NOT NULL,updated_at BIGINT NOT NULL);

CREATE TABLE IF NOT EXISTS workflow_steps (workflow_id VARCHAR(36) NOT NULL,position INT NOT NULL,code VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL,attempts INT NOT NULL DEFAULT 0,job_id VARCHAR(64),started_at BIGINT,completed_at BIGINT,error TEXT,PRIMARY KEY(workflow_id,position));

CREATE TABLE IF NOT EXISTS telegram_visitors (bot_id VARCHAR(32) NOT NULL,telegram_user_id VARCHAR(32) NOT NULL,user_id VARCHAR(36) NOT NULL,profile TEXT NOT NULL,first_seen_at BIGINT NOT NULL,last_seen_at BIGINT NOT NULL,PRIMARY KEY(bot_id,telegram_user_id));

CREATE TABLE IF NOT EXISTS business_events (id VARCHAR(36) PRIMARY KEY,event_key VARCHAR(64) NOT NULL UNIQUE,user_id VARCHAR(36) NOT NULL,project_id VARCHAR(36),bot_id VARCHAR(32),environment VARCHAR(16),version INT,type VARCHAR(32) NOT NULL,source VARCHAR(64),occurred_at BIGINT NOT NULL,data TEXT NOT NULL,raw_update TEXT);

CREATE TABLE IF NOT EXISTS business_dispatches (id VARCHAR(36) PRIMARY KEY,user_id VARCHAR(36) NOT NULL,kind VARCHAR(32) NOT NULL,status VARCHAR(16) NOT NULL,started_at BIGINT NOT NULL,completed_at BIGINT);

CREATE INDEX IF NOT EXISTS ix_apps_user ON telegram_apps (user_id,id);

CREATE INDEX IF NOT EXISTS ix_projects_user ON project_info (user_id,id);

CREATE INDEX IF NOT EXISTS ix_workflows_pending ON workflow_runs (status,next_at);

CREATE INDEX IF NOT EXISTS ix_events_user ON business_events (user_id,occurred_at);

CREATE INDEX IF NOT EXISTS ix_events_project ON business_events (project_id,occurred_at);

CREATE INDEX IF NOT EXISTS ix_dispatch_user ON business_dispatches (user_id,status);
